name: Build

on:
  workflow_dispatch:


jobs:
  buildpackage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install nativefier -g
      - name: Build
        run:  |
          nativefier --name lilegeli --portable https://lilegeli.netlify.app
          ls
          cd lilegeli-linux-x64
      - name: Package Bundle
        working-directory: .
        run: 7z a -tzip lilegeli-${{ runner.OS }}.zip lilegeli-${{ runner.OS }}-x64
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: lilegeli-${{ runner.OS }}-${{ runner.arch }}
          path: lilegeli-*.zip